### ISSUE TITLE
AssertionError: Loading a checkpoint for MP=0 but world size is 1

### ISSUE THREAD

**Issue by satori2017** [uiuc-arc/llm-code-watermark#15]
Traceback (most recent call last):
  File "llm-code-watermark/lpw/run_llama.py", line 125, in main
    evaluate_llama(ckpt_dir=ckpt_dir, tokenizer_path=tokenizer_path, result_dir=result_dir,num_samples_per_task=num_samples_per_task)
  File "llm-code-watermark/lpw/run_llama.py", line 79, in evaluate_llama
    generator = load(
  File "llm-code-watermark/lpw/run_llama.py", line 41, in load
    assert world_size == len(
AssertionError: Loading a checkpoint for MP=0 but world size is 1
It seems that the ckpt_dir:/share/models/llama_model/llama does not exist in file yet, and the missing chekpoint makes this assertionerror.

**Comment by tarsur909** [comment]
Hi, 

Please refer to the updated README.md file for the instructions. 

Hope this helps.
